# Generated by Django 4.2.7 on 2025-04-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='vuokraus_pl_name_6db6e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='vuokraus_ge_name_cc771a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('age_rating', models.PositiveSmallIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('description', models.TextField()),
                ('genre', models.ManyToManyField(to='vuokraus.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuokraus.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuokraus.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='vuokraus_lo_user_id_799e21_idx'), models.Index(fields=['game'], name='vuokraus_lo_game_id_1a3805_idx'), models.Index(fields=['returned_at'], name='vuokraus_lo_returne_829e98_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('user', 'game'), name='unique_active_loan'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='vuokraus_ga_title_c62166_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['platform'], name='vuokraus_ga_platfor_e8b5bb_idx'),
        ),
    ]
