# Generated by Django 5.2 on 2025-04-30 21:15

import django.db.models.deletion
import vuokraus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuokraus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=vuokraus.models.cover_upload_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vuokraus.platform'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vuokraus.game'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
